name: Print Secret Variable

on:
  pull_request:
    types: [opened, reopened]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret
        env:
          MY_VAL: ${{ secrets.FLAG }}
        run: |
          import os
          print(os.getenv("MY_VAL"))
        shell: python
