name: Secret Prints

on:
  pull_request:
    types: [opened, reopened]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Get Flag
        env:
          MY_VAL: ${{ secrets.FLAG }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
